<HTML>
<HEAD><TITLE>MY PEHELA FORM</TITLE></HEAD>
<BODY BGCOLOR=GREY>
<FORM ACTION="THANKYOU.HTML"METHOD="GET">
FIRST NAME:<INPUT TYPE="TEXT" NAME="NAME"><BR>
FAMILY NAME: <INPUT TYPE="TEXT" NAME="FNAME"><BR><BR>
GENDER:<BR>
<INPUT TYPE=RADIO NAME="G1"> MALE <BR>
<INPUT TYPE=RADIO NAME="G1"> FEMALE <BR> <BR>
HOBBIES:<BR>
<INPUT TYPE="CHECKBOX" NAME="C1"> DRAWING <BR>
<INPUT TYPE="CHECKBOX" NAME="C2"> SINGING <BR>
<INPUT TYPE="CHECKBOX" NAME="C3"> DANCING <BR>
<INPUT TYPE="CHECKBOX" NAME="C4"> READING <BR><BR>
<INPUT TYPE="SUBMIT" NAME="SUB">
</FORM>
</BODY>
</HTML>
